@startuml
title Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Клиент", "Клиент банка")
Person(backOffice, "Менеджер бэк-офиса")

System(webBank, "Интернет банк")
System(ABS, "АБС", "АБС система")
System(SMS, "SMS", "SMS шлюз")

Container_Boundary(webBank, "FitLife System") {
  Container(WebApp, "Web Application", "React, CSS", "клиенткая часть интеренет банка")
  Container(Service, "Service", "C#", "бэк-энд част интеренет бакнка")
  Container(DepositService, "Deposit Service", "C#", "сервис депозитов")
  Container(WebBankDatabase, "Database", "MS SQL", "БД сервиса депозитов")
}

Container_Boundary(ABS, "FitLife System") {
  Container(ABSWebApp, "Web Application", "React, CSS", "клиенткая часть АБС")
  Container(ABSService, "ABS Service", "Delphi", "сервис АБС")
  Container(Database, "Database", "Oracle", "БД для АБС")
}

Rel(user, webBank, "работа клиента с интернет баком")
Rel(backOffice, ABSWebApp, "работа менеджера с сервисами abs")
Rel(ABSWebApp, ABS, "взаимодействие бэк-фронт")

Rel(WebApp, Service,"взаимодействие бэк-фронт")
Rel(Service, DepositService,"работа с сервисов депозитов")
Rel(DepositService, WebBankDatabase, "Запись/Чтение БД")

Rel(DepositService, ABSService, "Взаимодействие с АБС")
Rel(ABSService, Database, "Запись/Чтение БД")

Rel(ABSService, SMS, "")
Rel(SMS, user, "Отправка смс клиенту")
@enduml